### ISSUE TITLE
facebook app settings

### ISSUE THREAD

**Issue by durnezj** [elaniin/AccountKit-Web-PHP#2]
What are your settings in the facebook developpers console? My account kit doesn't work and the fault is in the facebook app settings but i don't know the correct settings, i always get an error when the i click the button and the popup opens.

**Comment by elaniin** [comment]
Hi,

There are 2 parts of setting for your Accont Kit configuration.

1. In the "settings" section, the **App Domain** and the "Site URL" are the important things.
![accountkitphp_configuration](https://cloud.githubusercontent.com/assets/5340847/15274575/a170bd8e-1a72-11e6-88a9-9b1c8bc012a1.png).

2. In the "Account Kit" section, check how my settings are.
![accountkitphp_configuration2](https://cloud.githubusercontent.com/assets/5340847/15274587/f4bd9b1a-1a72-11e6-89bf-c430cf99580b.png)

Let me know if that help and now works for you.

**Comment by elaniin** [comment]
Another thing,

In the **Account Kit** section you need to add your domain in the **Server URLs** field.
In my example I added http://toolboxsv.com/, https://toolboxsv.com/, http://www.toolboxsv.com/, https://toolboxsv.com/, because i want my integration work with https and http, and www or without www.
![accountkitphp_configuration3](https://cloud.githubusercontent.com/assets/5340847/15274599/5ce67374-1a73-11e6-8fa2-b5a4df2e02a9.png)

**Comment by durnezj** [comment]
Thanks for your answer, I'll let you know as soon as i am able to work on it

**Comment by durnezj** [comment]
Thank you so much, my problem has been resolved and it is workig now!
